sudo: false

language: node_js

node_js:
  - '10'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run checkFormat
  - npm run build
  - npm test
